global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'telco_churn_model'
    static_configs:
      # PENTING: Jangan pakai localhost, tapi nama service di docker-compose nanti
      - targets: ['model_app:8000']