# global:
#   scrape_interval: 5s 

# scrape_configs:
#   - job_name: 'telco_churn_monitoring'
#     static_configs:
#       - targets: ['localhost:8000'] # IP dan Port script exporter.py


global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'telco_churn_model'
    static_configs:
      # PENTING: Jangan pakai localhost, tapi nama service di docker-compose nanti
      - targets: ['model_app:8000']